### ISSUE TITLE
Waiting for the code!

### ISSUE THREAD

**Issue by Pamogar** [stefan-ainetter/SCANnotate#1]
First of all, thank you for your great work and congratulations on the paper!

When are you planning to release the code? Looking forward to it!

**Comment by stefan-ainetter** [comment]
Hi @Pamogar,

Thank you very much for your interest. We are currently in the process of cleaning the code and setting up a convenient structure for the data. 
After this is done, we will release the code (which will be in a few weeks I believe).

**Comment by stefan-ainetter** [comment]
Code is available now, closing this issue.
