### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by claragarciamoll** [stefan-ainetter/SCANnotate#2]
Hello. First of all, congrats on your amazing job. Currently, I am working on the alignment between CAD models and RGB-D scans.

For this reason, I am interested in when you plan to release the code.

I appreciate any help you can provide.

**Comment by stefan-ainetter** [comment]
Hi @claragarciamoll,

Thank you for your interest! Code is available now. If you have any additional questions, feel free to open another issue.
