### ISSUE TITLE
Code for ScanNet preprocessed

### ISSUE THREAD

**Issue by sayands** [stefan-ainetter/SCANnotate#4]
Hello, 

Thanks for your nice work! I had one question - how do you preprocess the ScanNet dataset as in provided example, specifically ``preprocessed`` folder and if the code for that could be made publicly available? Please let me know, thank you.

**Comment by florianlanger** [comment]
I have exactly the same question. Would be great if you could make that code publicly available too. Thanks!

**Comment by stefan-ainetter** [comment]
Hi,

thank you for your interest! Currently, we do not plan to release the code for preprocessing the scenes, we might do this at some point in the future. However, you can find general information about the preprocessing in the supplementary material of the paper, and maybe issue #3 is also interesting for you.
